### ISSUE TITLE
Detect silent audio tracks and make zero-length

### ISSUE THREAD

**Issue by mtolly** [mtolly/onyxite-customs#100]
This could be done either

1. when importing the CON file; e.g. if bass uses channels 4 and 5 of a MOGG, then when we import it into an Onyx project we scan those channels (if we can read the MOGG) and if they have no audio we give bass an empty channel list instead.
2. when generating the Magma project; e.g. when creating `gen/target/mogg/magma/bass.wav` we first scan the audio stream and if we get through the whole thing without finding sound then emit a zero-length file.

I'm leaning towards option 1 but either would work.

**Comment by inertlab** [comment]
hi, 

i just tried onyxite and it created silent ogg files. is this normal?
