### ISSUE TITLE
[REQUEST] More Hiromi! (and updates)

### ISSUE THREAD

**Issue by Rhystic1** [mtolly/onyxite-customs#130]
Hello,

First, I apologise if this is not the right place to post this.

I'm a huge fan of your work, and Hiromi is one of my favourite jazz artists. I was wondering if you had any plans on adding more from the "Brain" album (my favourite) and/or add more Pro Bass support. Thanks!

**Comment by mtolly** [comment]
Hi there, answers are definitely yes to both of those :) I have several Hiromi in progress and planned from a few different albums, and also a whole bunch of PG/PB in the works. Very glad to hear from people playing protar charts!
