### ISSUE TITLE
plan with split drum kit has invalid channel counts

### ISSUE THREAD

**Issue by boogaboo7** [mtolly/onyxite-customs#143]
MIDI auto-detected as RB Overdrive format, passing through unmodified
ERROR! Plan with split drum kit has invalid channel counts: (kick,snare,kit) = (2,0,2)
Context (innermost first):

**Comment by mtolly** [comment]
@boogaboo7 Can you post a link to the song that causes this?

**Comment by mtolly** [comment]
This should be fixed now in `20210606`.
