### ISSUE TITLE
Can't move or delete generated files

### ISSUE THREAD

**Issue by MasterBuller** [mtolly/onyxite-customs#161]
Unable to move or delete files that the program generates, so I advice to not download and install this program.
Using it on Windows 10, now sadly I have 7 files tainting my desktop thanks to this program.

**Comment by MasterBuller** [comment]
Had to open the resource editor in order to fix the issue, but still, I don't recommend this software
![Screenshot](https://user-images.githubusercontent.com/69060738/89087240-d86ba880-d350-11ea-9397-d844089abc32.jpg)

**Comment by mtolly** [comment]
Yeah, I haven't heard of anyone else having a problem like this. I'm not sure what strange permissions settings you have on your desktop, but I'm 99% sure it's not the program's fault.
Also, don't post pictures like that.
