### ISSUE TITLE
Potential support for Fuser?

### ISSUE THREAD

**Issue by Lordmau5** [mtolly/onyxite-customs#164]
So seeing as Fuser is another rhythm game by Harmonix, albeit not one where you need extra peripherals and have to hit notes to the beat, I thought I'd just open an issue in regards to this.

The files, which appear to be `.uexp` files (some Unreal Engine format), have some encrypted MOGG data in them.
There's also some extra info at the start of the file, which appears to be potentially holding some encryption related info and some "original file" path.
Additionally, towards the end of the file there is some plain-text info about the song itself - such as the `root_note` or `orig_temp` to have it sync up ingame.

I fully understand if there would be no consideration to potentially include tools that would assist in the en-/decryption of this game, but seeing as the repository mentioned `Harmonix's Rock Band 3 and other similar rhythm games` I thought it would be a good place to start.

On top of that, the game released around 9 days ago and someone else has already done a post on the ZenHAX forums in regards to potentially getting a QuickBMS script to run, but so far there are no responses to that sadly...

I've also attached an archive with the `.uexp` file in case you would like to look around in it and see if perhaps a modification to the `SongCrypt` file could make this work...

[trans_BustAMove_LOOP_Em_120_fusion.zip](https://github.com/mtolly/onyxite-customs/files/5567838/trans_BustAMove_LOOP_Em_120_fusion.zip)

**Comment by DioGiorno** [comment]
how do I use SongCrypt to decrypt my paid songs from Rock Band 2?

**Comment by mtolly** [comment]
Yeah, I'd be interested and it looks very cool, but it seems off topic for Onyx, or rather there wouldn't be much gained from being tied to it. In general I'm not gonna add tools to decrypt audio files, to try to avoid legal issues / takedowns.

But, you should join these Discords if you have not already - https://discord.gg/5exdSww8Fs (Fuser/DropMix modding) https://discord.gg/TgQnpG2q7f (Harmonix GH/RB/etc.) - there might be other people there interested.

**Comment by Lordmau5** [comment]
Thank you for the response on this!
And yeah, I really had my doubts about you wanting to support it but I thought I'd ask anyway 😁
