### ISSUE TITLE
How do I use SongCrypt?

### ISSUE THREAD

**Issue by DioGiorno** [mtolly/onyxite-customs#165]
I'm confused asf with this application, I had my paid songs ready to decrypt them. The reason why I need stems from this file is because some songs that originally has Crowd audio is missing from Chorus site so I just need to rip that audio out.

**Comment by mtolly** [comment]
I'm not sure what you're referring to - Onyx doesn't support any encrypted audio files. There are decryption tools floating around that only work for early RB songs, but I can't help with that.
