### ISSUE TITLE
Midi compiler error (Part Vocals)

### ISSUE THREAD

**Issue by Joshwantsmaccas** [mtolly/onyxite-customs#169]
I have tried redoing the vocals on the same mid file, a brand new one more times than I would like to admit but I always get these same issues at the same time stamps, currently I am stumped as I have done everything I think I can to rectify it. here's my task view:  (Files included) 

[For The Likes Of You - Habitual Gloom.zip](https://github.com/mtolly/onyxite-customs/files/5828120/For.The.Likes.Of.You.-.Habitual.Gloom.zip)

Task 1: C:\Users\Josh\Documents\My Charts\Guitar and Drums\me only\For The Likes Of You - Habitual Gloom
Importing FoF/PS/CH song from folder: C:\Users\Josh\Documents\My Charts\Guitar and Drums\me only\For The Likes Of You - Habitual Gloom
Found song.ini and notes.mid
Star Power note specified in song.ini to be 116 (RB format)
Warning: Vocal phrase edges extended to be a minimum length of 1 beat
Context (innermost first):
  - [58:3:000], [58:3:234], [60:3:000], [60:4:234], [62:4:000], [64:1:360], [64:2:006], [64:2:360], [64:4:006], [66:2:000], [67:1:075], [67:3:360], [67:4:366], [69:1:300], [69:2:136], [69:4:420], [71:3:016], [73:1:420], [73:2:252], [74:3:420], [75:1:016], [76:4:240], [77:1:256], [78:2:420], [79:2:256], [81:1:060], [81:2:252], [82:4:300], [83:2:256], [84:4:390], [85:1:210], [86:2:340], [86:3:054], [87:2:090], [87:3:100], [87:4:270], [88:1:045], [88:3:030], [88:3:405], [89:1:090], [89:1:459], [89:3:150], [89:4:100], [90:2:090], [90:2:396], [90:4:210], [90:4:400], [91:3:030], [91:4:045], [91:4:450], [92:1:396], [92:3:390], [94:2:405], [96:1:390], [96:2:400], [98:2:030], [98:3:400], [99:4:390], [100:2:396], [101:2:270], [101:2:396], [104:2:270], [104:3:165], [107:2:150], [107:2:400], [108:3:270]
  - Track PART VOCALS
Loading the MIDI file...
Found audio file "guitar.ogg" at: ["C:\\Users\\Josh\\AppData\\Local\\Temp\\onyx-c2d1adfe5abb5e5b\\guitar.ogg"]
Warning: Placing [end] at [76:1:000]. Last MIDI event is at [73:1:270], longest audio file ends at [75:2:324], minimum Magma length (30s) is [11:5:450]
Context (innermost first):
  - Processing MIDI for RB3/PS
Warning: No BEAT track found; automatic one generated from time signatures.
Context (innermost first):
  - Processing MIDI for RB3/PS
Warning: [music_start] is missing. Placing at [1:3:000]
Context (innermost first):
  - Processing MIDI for RB3/PS
Warning: [music_end] is missing. [end] is at [76:1:000] so [music_end] will be at [75:5:000]
Context (innermost first):
  - Processing MIDI for RB3/PS
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/guitar.wav
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/bass.wav
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/vocal.wav
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/drums.wav
Finished writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/drums.wav
Finished writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/vocal.wav
Finished writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/guitar.wav
Finished writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/bass.wav
Found audio file "guitar.ogg" at: ["C:\\Users\\Josh\\AppData\\Local\\Temp\\onyx-c2d1adfe5abb5e5b\\guitar.ogg"]
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/plan/fof/countin.wav
Finished writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/plan/fof/countin.wav
Writing audio to C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/magma/song-countin.wav
# Running Magma v2 to export MIDI
ERROR! process exited with code 1
stdout:
Reading the archive
SystemInit Params: C:\Users\Josh\AppData\Local\Temp\magma-85bd278a9d3c73ba\MagmaCompilerC3.exe -export_midi C:\Users\Josh\AppData\Local\Temp\onyx-c2d1adfe5abb5e5b\gen/target\43401536\magma/magma.rbproj C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/notes-magma-export.mid
MIDI Compiler: Starting...
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [41:1:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [43:3:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [43:4:006] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [44:5:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [45:5:180] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [46:4:468] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [47:2:180] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [49:2:240] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [50:2:240] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [51:6:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [52:5:240] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [54:3:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [55:4:240] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [57:1:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [58:2:162] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [58:5:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [58:6:030] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [59:2:150] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [59:4:390] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [59:6:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [60:1:030] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [60:3:000] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [60:3:090] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [60:5:420] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [60:6:030] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [61:2:090] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [61:4:450] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [61:6:390] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [62:3:330] is outside any phrases
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [64:4:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [65:4:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [66:6:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [67:6:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [69:6:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [71:4:390] extends beyond phrase
ERROR: MIDI Compiler: (PART VOCALS): Vocal note at [72:2:400] extends beyond phrase
MIDI Compiler: Done.

stderr:

Context (innermost first):
  - running Magma v2 to export MIDI
  - shake: C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/notes-magma-export.mid
  - shake: C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/notes-magma-added.mid
  - shake: C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/stfs/songs/o166452114/o166452114.mid
  - shake: C:/Users/Josh/AppData/Local/Temp/onyx-c2d1adfe5abb5e5b/gen/target/43401536/rb3con

**Comment by mtolly** [comment]
It looks like there is a bug in my code that is supposed to ensure vocal phrases are at least 1 beat (fix for issue #131). So a whole bunch of phrases are being moved to the wrong places. Working on a fix now. I don't know if EOF lets you control exactly where the phrase bounds are in the `notes.mid` it creates, or if they are automatic - if you can control the bounds you can work around the bug until I get the fix out by ensuring all phrases last at least 1 quarter note (for example the one at `58.3.00 (1:46.158)` is too short for Magma).

Also, unrelated, but I see there is a bug in how the `delay` feature of `song.ini` is implemented which causes the error positions reported by Magma to be wrong (it turns the 4/4 time signature into 6/4 to add space in front, but then doesn't change it back...) so I'll fix that as well.

**Comment by Joshwantsmaccas** [comment]
Thanks for checking it out and getting back to me, always appreciated! I think there is an option like that in eof, so i'll for sure check that out first!
as for the delay error I had no idea, again thank you for the help and fixes!

**Comment by mtolly** [comment]
I need to fix a few more things elsewhere before I can do a normal release with the bug fix, but here is a version that fixes both of the charts you uploaded.
https://onyxite.org/tmp/onyx-20210213-windows-x64.exe

**Comment by Joshwantsmaccas** [comment]
> I need to fix a few more things elsewhere before I can do a normal release with the bug fix, but here is a version that fixes both of the charts you uploaded.
> https://onyxite.org/tmp/onyx-20210213-windows-x64.exe

Thankyou! Hugely Appreciated!!!

**Comment by mtolly** [comment]
Closing as both of these fixes are in the just-released `20210522`.
