### ISSUE TITLE
ERROR! Plan with split drum kit has invalid channel counts

### ISSUE THREAD

**Issue by Slash8789** [mtolly/onyxite-customs#173]
I  get this error message when trying to create some Magma projects for Xbox 360. Any suggestions?

**Comment by mtolly** [comment]
Can you send a link to the affected song? This can sometimes happen with Guitar Hero rips in CH/PS format, depending on how the stems are set up.

**Comment by Slash8789** [comment]
I'll try to send it sometime this week.

**Comment by mtolly** [comment]
This should be fixed now in `20210606`.
