### ISSUE TITLE
ERROR! Plan with split drum kit has invalid channel counts: (kick,snare,kit) = (2,0,2)

### ISSUE THREAD

**Issue by DawgzRule** [mtolly/onyxite-customs#175]
I am receiving this error when converting to RB3con for the following files:

https://drive.google.com/file/d/1IOpSFZyNX5l5_CFsbUJ1r8d0vE8y4ZTo/view

https://drive.google.com/file/d/19s_aN-8CBZEyHHlKqueuDe9k5b9CESzH/view

https://drive.google.com/file/d/1UdjOxpHKC1SzfR7KXfCkvI3w-2plWZ2r/view

**Comment by mtolly** [comment]
Thanks for the test cases. I think I have a fix for this (mixing down the drums audio if it's in a configuration not directly supported by Rock Band) that will be in a release soon.

**Comment by DawgzRule** [comment]
I was able to get two of them to work by removing the 2x drum ogg.   Sing turned out not to be a drum issue.  Instead, it was the keys.ogg.   I converted without the keys and it worked.

**Comment by mtolly** [comment]
This should be fixed now in `20210606`.

**Comment by DawgzRule** [comment]
Thank you!!   Have a great rest of your week.
