### ISSUE TITLE
Unable to select file on Mac

### ISSUE THREAD

**Issue by Casuallynoted** [mtolly/onyxite-customs#177]
When attempting to load a DTX file on Mac, nothing happens. I'm prompted to select an file and hit open, but the console does not update and the program does not react as though anything has been loaded. Provided Onyx with full disk access via system preferences but the issue persists. Running on macOS Monterey, on M1.

**Comment by mtolly** [comment]
It looks like I forgot to add some kind of "Loading..." message when beginning the audio convert process from DTX, so it may just be taking a while to do that.

If you waited a few minutes and still nothing happens, I would try loading a different file type, like a Clone Hero folder from http://chorus.fightthe.pw/ and see if that works. Also, try dragging and dropping a folder onto the "Load a song" button which should do the same thing as browsing to it.

If none of those work there may be some new compatibility issue - I have neither an M1 nor a system running Monterey so unfortunately it may be a while before I can troubleshoot.

**Comment by mtolly** [comment]
This is finally fixed in the build I just put up of `20220319`. Turns out it was only the file select prompt that broke, while drag and drop was fine. Let me know if there's still a problem.
