### ISSUE TITLE
Output conversion without audio when "encrypted MOGG (type 0xD) not supported"

### ISSUE THREAD

**Issue by MWers** [mtolly/onyxite-customs#184]
For song conversions that fail with `ERROR! moggToOgg: encrypted MOGG (type 0xD) not supported`, is there a way to complete the conversion without including the audio file(s)? 

In my case, I'm converting songs from RB3 to Clone Hero. It would be very useful to still output the Clone Hero folder containing `song.ini`, `album.png`, and `notes.mid` without `*.ogg`. 

Is this possible?

Thanks!

**Comment by aure** [comment]
What would be involved in making the mogg types that are not yet supported work?  There seems to be a lot of songs using this types, so it would be a great addition to Onyx's functionality. If there's anything I could to help let me know.

**Comment by mtolly** [comment]
@MWers Thanks for the suggestion, this will be an option in the next build soon.

@aure At the moment I'm not interested in adding .mogg decryption support to Onyx - unfortunately Harmonix has made legal threats against similar projects in the past, so I'd like to steer clear of that for now. I might change my position on that in the future though, if it seems like it is safer. At the moment the typical workarounds are:

* For official RB DLC and RBN content, import from an existing Clone Hero format rip. Most of these can be found on https://chorus.fightthe.pw/
* For custom songs using C3's encryption, use C3 CON Tools to convert to Phase Shift format (which mixes the audio down to a single track). Then Onyx can import from that

**Comment by aure** [comment]
Makes sense to me. I have about 100 songs which I can't find in any format but that mogg. I'll live without them. :)

**Comment by mtolly** [comment]
Added in `20220311`, see Edit > Preferences > Audio

**Comment by aure** [comment]
Anxiously awaiting a Mac Monterey compatible release... Thanks!

**Comment by MWers** [comment]
@mtolly I missed your response earlier. Just wanted to say thanks and keep up the great work!

**Comment by mtolly** [comment]
Noting here, Onyx now supports typical RB encrypted MOGGs in version `20240719`
