### ISSUE TITLE
No way to change the gender for singer (RB3)

### ISSUE THREAD

**Issue by TheGuitarHeroNerd** [mtolly/onyxite-customs#185]
When making RB3 customs there is no way to change the gender in the toolkit.

My idea would be to add the option in the instruments tab just like how you can select the drum toolkit.

![image](https://user-images.githubusercontent.com/73220666/140701000-12b3e786-3ff4-4182-a913-85fb4ab71cf2.png)

**Comment by mtolly** [comment]
This is added in build `20221023`
