### ISSUE TITLE
About DTX File Conversions

### ISSUE THREAD

**Issue by sakamoto-neko** [mtolly/onyxite-customs#190]
I've tried a few DTX conversions and they work really well. When I convert some DTX files, I realize sometimes the cymbal placements generated by Onyx feel a bit off. I would like to suggest a "manual" type of conversion, where

e.g. All DTX hi-hat notes automatically go to yellow cymbal,
All DTX left cymbal notes automatically go to blue cymbal, and
All DTX right cymbal notes automatically go to green cymbal.

I'm requesting this as I'm familiar with HMX's guidelines for charting drums, and it would be easier for me to finetune the charts via DTXCreator before converting them through Onyx.

**Comment by mtolly** [comment]
Hey, yeah that makes sense, I can absolutely add that. I'm glad to hear someone is using the DTX support!

I'm hoping to get a build out soonish with a bunch of fixes/features and will try to get that in, so I'll ping here when it's up.

**Comment by mtolly** [comment]
This is now up in `20220311`, it is used by default (might add an option for the previous assignment method in the future, but this seems more useful). Let me know if any other changes are needed.
