### ISSUE TITLE
ERROR! Exception {errorString = "File contains data in an unimplemented format."}

### ISSUE THREAD

**Issue by Fireqc** [mtolly/onyxite-customs#205]
Got this after tried to convert this song in CloneHero format.
I'm running Ubuntu 20.04 and the link for the song:
https://dl.c3universe.com/s/fbs13/songofthesirens/WeAreTheOthers_rb3con

Please tell me what I'm doing wrong?

**Comment by mtolly** [comment]
Thank you for reporting this, you didn't do anything wrong - something seems to have gone wrong when I compiled the Linux version and the library used for creating `.ogg` files is not working (which breaks both CH to RB and RB to CH). I'll figure out what happened and get a fixed build out ASAP.

**Comment by mtolly** [comment]
I'll hopefully get a new version that is fixed up this week, but in the meantime I confirmed that the previous version `20220319` works correctly, which you can download [here](https://github.com/mtolly/onyxite-customs/releases/download/20220319/onyx-20220319-linux-x64.AppImage).

**Comment by Fireqc** [comment]
You're absolutely right!  This version works like a charm.
Many thanks!

FIRE.................

**Comment by mtolly** [comment]
This should be fixed going forward from version `20220807`.
