### ISSUE TITLE
Feature Request: Duplicate Overdrive phrases across all Pro Keys difficulties when converting from RB3 to Phase Shift

### ISSUE THREAD

**Issue by Computerdude77** [mtolly/onyxite-customs#211]
This is going to be a weird request, so I will explain in detail what I mean here. When playing non-Expert Pro Keys charts on Phase Shift that are converted from Rock Band 3, the overdrive phrases are not present. As far as I can tell, this is because RB3 only charts the overdrive phrases on the Expert chart and uses that for the other difficulties (which carries over in the convert), but PS reads them separately, and as a result, none of the other difficulties have the phrases in. Here are some videos of that in action using [Babs Seed](https://db.c3universe.com/song/babs-seed-6281) as my test song because it has a phrase near the beginning. I did use a version that was converted to PS using Onyx and not C3 CON Tools (which has the same issue):

RB3:
https://user-images.githubusercontent.com/55714746/193527458-8ae94f78-a73b-4ea6-a6fa-6f57ffdf8263.mp4

Phase Shift:
https://user-images.githubusercontent.com/55714746/193527501-27a85ecd-ffac-46d4-8d49-d9005190c213.mp4

Something else to note that I did not record a video for, if I edited the chart manually to add the phrases into the other difficulties, it would read the phrase separately, so it was seemly an oversight from the developers that it doesn't read the phrases exactly the same way. With all that being said, here is the request, an option to copy the phrases across all difficulties when converting to PS, potentially as a checkmark option, or something along those lines. The reason I say that is because I tested what happens if you try to convert a chart with this modification back to an RB3con, and it gives an error about the notes being out of bounds, likely as it was never intended to have separate overdrive for all difficulties. I guess on a related note, a similar option could be added to RB3 conversion to ignore those parts, but I doubt that situation would arise much and I don't mind if that isn't added. If this request is too much to implement/impractical, I totally understand, as this is an issue that I'm sure not many people will run into. Apologies for the wall of text, but I wanted to be as thorough as possible when explaining the request. Have a good day!

**Comment by mtolly** [comment]
Thanks for the report, yes this makes sense and I can just have it copy them to lower difficulties for PS format in the next build.

**Comment by mtolly** [comment]
Done in build `20221230`
