### ISSUE TITLE
Feature Request: Support Encrypted MOGGs

### ISSUE THREAD

**Issue by MystiK791** [mtolly/onyxite-customs#213]
Extracting/converting songs from Rockband 3/LEGO Rockband will result in an error if using the Xbox 360 versions of the game, due to the MOGGs being encrpyted. If I go into the appdata folder and decrypt them manually, the songs will convert just fine. I'd like there to be a way for Onyx to auto-decrypt the MOGG files so that I don't have to manually place **45** decrypted MOGGs into the Appdata folders. R3 CON tools can decrypt MOGGs, but the tool was never open-sourced unfortunately.

Thanks!

**Comment by mtolly** [comment]
Sorry, as mentioned in other issues I won't be adding Rock Band decryption support at the moment due to legal concerns.

**Comment by MysticAx0lotl** [comment]
Two years later :P
