### ISSUE TITLE
"getShortPathName: does not exist" when creating GH3 cache (PS3)

### ISSUE THREAD

**Issue by LlysiX** [mtolly/onyxite-customs#215]
The title says almost everything about this issue.

![unknown](https://user-images.githubusercontent.com/79173634/197593953-80a3f6c3-bc41-4298-b9d9-50b672a9c53d.png)

I've tried loading just one song, just official DLC (+rap files), just customs. No matter what, attempting to create a GH3 cache PKG for PS3 causes this error to show up.
The onyx logs (main window and task window) show nothing.

**Comment by LlysiX** [comment]
Just in case it's needed, here's a screenshot of the tools window when the error shows
![image](https://user-images.githubusercontent.com/79173634/197617209-08763825-f665-4b6f-a40a-cbaafbddf328.png)

**Comment by mtolly** [comment]
Thank you, this should be fixed in `20221024`.
