### ISSUE TITLE
Audio tracks swapped at converting PS/CH format to RB3CON format

### ISSUE THREAD

**Issue by GeeForce11** [mtolly/onyxite-customs#217]
Noticed a few bugs by swapping audio tracks during converting:
In case of 6 or 7 channel audio keys track gets swapped with vocals track at converting
In case of singletrack audio, backing and crowd track, they get swapped at converting
In case of singletrack audio, only backing, audio becomes mono backing at converting

The newest version 1023 wouldn't even open a PS/CH format song.ini project like all previous versions open normally, the new version gets an error "no song found" had to go back to the previous version temporarily

**Comment by GeeForce11** [comment]
![6ch Audio](https://user-images.githubusercontent.com/116615199/197898400-8697fa5c-65f6-475e-9d49-25243b161fa9.jpg)

When converting a 6ch audio onyx puts the keys stem on track#6-7 where usually the vocal track is and puts the vocal stem on track #8-9 where usually the keys track is, this is how C3 CON tools reads the mogg in the con

**Comment by GeeForce11** [comment]
![1ch w crowd](https://user-images.githubusercontent.com/116615199/197904495-6ca0ee52-0850-4bd0-af9e-3ceea1bb5f51.jpg)

When converting a singletrack audio onyx puts the crowd stem on track#3-4 where usually the backing track is and puts the backing stem on track#5-6 where usually the crowd track is, this is how C3 CON tools reads the mogg in the con

**Comment by mtolly** [comment]
I don't understand what the actual problem you're describing is - I see that the track order output by Onyx is different than it may have been in official files, but this shouldn't matter - as long as the channel indexes are correct (which they seem to be as far as I can tell) there should be no problem.

Is C3 CON Tools reading the songs.dta to apply those labels to the tracks? Is anything actually wrong in game?

**Comment by GeeForce11** [comment]
Maybe C3 con tools doesn't read the indexes correctly from the dta and assuming the order of the track in the midi associates it to the usual channel, but it does get swapped around when converting back the con to PS/CH format with C3 tools.

I guess the solution for the glitch is in case of 6channel audio that onyx should put the vocal stems in the mogg to track #6-7, keys stem to track#8-9, backing to 10-11 and crowd to 12-13 if there is and index it accordingly in the dta in the example posted before

I guess the solution for the glitch is in case of 1ch audio with crowd track that onyx should put the backing stem in the mogg to track #3-4 and crowd to 5-6 and index it accordingly in the dta in the example posted before

**Comment by mtolly** [comment]
I see; I can probably get them rearranged for better compatibility in that case. But yes this is really an issue in C3 CON Tools and something that would be good if they fixed on their end.

For reference, from a quick check in the public codebase,
* [audio analyzer code](https://github.com/RBTools/CON-Tools/blob/14dd538ee929093808b67e96691620321d41aa54/C3%20Tools/AudioAnalyzer.cs#L165) that seems to assume the fixed order
* [Phase Shift mogg splitter code](https://github.com/RBTools/CON-Tools/blob/14dd538ee929093808b67e96691620321d41aa54/C3%20Tools/MoggSplitter.cs#L256) that does the same

**Comment by GeeForce11** [comment]
It does seem like the glitch is in C3 tools, it would make sense to re arrange the order of the tracks in the mogg for better compatibility, following the track order of the official files.

**Comment by mtolly** [comment]
Updated in build `20221230` to use the Harmonix/Magma order.
