### ISSUE TITLE
[Power Gig] A.V.H. fails to convert

### ISSUE THREAD

**Issue by murlatok** [mtolly/onyxite-customs#220]
Ozzy Osbourne - A.V.H. always fails to convert to any format whenever throwing Data.hdr.e.2 file into onyx (tried bot with X360 and PS3 files). Conversion won't start and i just get the error message

![777777777777777777777777777777777](https://user-images.githubusercontent.com/96484464/198248257-abaa6156-60f0-4c2b-93f5-0fbd4fdd6191.png)

**Comment by JohnSmith2007** [comment]
Bruh, you're trying to convert a song from Power Gig. The game isn't supported by Onyx. [I think?]

**Comment by mtolly** [comment]
Thank you for the report, this will be fixed in the next release.

**Comment by mtolly** [comment]
Should be fixed in build `20221230`
