### ISSUE TITLE
Regression: Cannot convert from phase shift

### ISSUE THREAD

**Issue by AARP41298** [mtolly/onyxite-customs#224]
Console:
`Warning: Failed reading: ; Converted using C3 CON Tools' Phase Shift Converter`
`ERROR! No songs found!`

I usually use onyx for the non encrypted songs and C3 for encrypted ones
But there are some (that i call) buged encrypted songs that crash rpcs3
That why i first convert them to phase shift, then to pkg

**Comment by AARP41298** [comment]
Temporary solution, edit song.ini and delete the comments (the lines that start with `;` )

**Comment by mtolly** [comment]
Thanks for the report. I'm not sure if these were added in a newer C3 CON Tools version or if I just never noticed... But this will be fixed in the next build (soonish?)

**Comment by mtolly** [comment]
Should be fixed in build `20221230`
