### ISSUE TITLE
Question on Beatles Rockband Files

### ISSUE THREAD

**Issue by giraffehere** [mtolly/onyxite-customs#227]
Hi there, thanks for this amazing tool. Have been using it to convert raw files (files that have the .ogg information in a folder, is that the LIVE format? I don't know the terminology) to Rockband 2 CON files for my Xbox 360.

Question on specifically the Beatles Rockband. I can successfully convert Beatles Rockband files through the Rockband 2 converter, but it shows up as Rockband 2 on my Xbox 360 and not on the Beatles Rockband game.

Is there a tweak that could be done to have it appear under Beatles Rockband? I haven't tested if the files work in Rockband 2, which would be fine, but figured I'd ask if it's possible to have them fall under Beatles Rockband.

Thanks!

**Comment by mtolly** [comment]
Hey, glad to hear of people getting use out of it :)

* If you have song folders with .ogg files inside, that is probably in Clone Hero format (aka Phase Shift or Frets on Fire format).

* Beatles RB files have some different requirements and as far as I know, RB2 files (either official or generated by Onyx) probably won't work in it without some changes. I do actually plan on adding Beatles as its own output format in the (near?) future - however note that, unlike RB2 and RB3, these will still require a jailbroken ("RGH") Xbox 360 to play.

**Comment by giraffehere** [comment]
Ah okay, makes sense. Appreciate the response and thanks again for the great app!
