### ISSUE TITLE
Issues with Rock Revolution conversion to Rock Band

### ISSUE THREAD

**Issue by rb4dlcfan** [mtolly/onyxite-customs#234]
Some songs from Rock Revolution like Dirty Little Secret, Blitzkrieg Bop and Heading Out to the Highway have an issue when converted to Rock Band, specifically the audio and the notes are desynchronized.

The song starts normally, but the gems appear later than they should be.

The following message appears in Onyx's log: Warning: Padding song by 1s due to early notes.

Is there any way to fix this?

**Comment by mtolly** [comment]
Thanks for reporting this, looks like there is a bug where it fails to add silence to the start of the audio when it comes from the XMA format that Rock Revolution uses. This will be fixed in the next build (soon-ish?)

**Comment by rb4dlcfan** [comment]
Thank you!

**Comment by mtolly** [comment]
This should be fixed in the new build `20230331`
